-- Issuer session IDs are signed claims. Device UUIDs are generated by this
-- service, never supplied by a client. Tombstones prevent refresh resurrection.
CREATE TABLE identity_sessions (
    issuer text NOT NULL,
    subject text NOT NULL,
    session_id text NOT NULL CHECK (length(session_id) BETWEEN 1 AND 512),
    account_id uuid NOT NULL,
    device_id uuid NOT NULL,
    PRIMARY KEY (issuer,subject,session_id),
    FOREIGN KEY (issuer,subject) REFERENCES identities(issuer,subject),
    FOREIGN KEY (account_id,device_id) REFERENCES devices(account_id,id)
);
CREATE INDEX identity_sessions_device_idx ON identity_sessions(account_id,device_id);
